import { test, expect } from '@playwright/test'

test('remembers a rescued spirit and only offers the chosen skill', async ({ page }) => {
  await page.goto('/')
  const demo = page.getByRole('region', { name: 'Play The Last Threshold' })
  await demo.getByRole('button', { name: 'Blade — cross the bridge of sentries' }).click()
  await demo.getByRole('button', { name: 'Fight through. Cut the spirit free.' }).click()
  await expect(demo).toContainText('They called you the Last Blade')
  await demo.getByRole('button', { name: 'Approach the throne together' }).click()

  await expect(demo.getByRole('button', { name: 'Sever its shadow with your blade' })).toBeVisible()
  await expect(demo.getByRole('button', { name: 'Let the spirit speak your true name' })).toBeVisible()
  await expect(demo.getByRole('button', { name: 'Slip into its shadow and strike' })).toHaveCount(0)
  await expect(demo.getByRole('button', { name: 'Burn the darkness with your last ember' })).toHaveCount(0)
  await expect(demo.getByRole('button', { name: 'Fit the stolen sigil into the crown' })).toHaveCount(0)
  await demo.getByRole('button', { name: 'Sever its shadow with your blade' }).click()
  await expect(demo).toContainText('a thousand sleeping souls walk home')
})

test('clears skills and remembered allies on restart, changing the next outcome', async ({ page }) => {
  await page.goto('/')
  const demo = page.locator('#try-it')
  await demo.getByRole('button', { name: 'Shadow — climb the haunted stair' }).click()
  await demo.getByRole('button', { name: 'Hide the spirit in your shadow' }).click()
  await demo.getByRole('button', { name: 'Approach the throne together' }).click()
  await demo.getByRole('button', { name: 'Slip into its shadow and strike' }).click()
  await expect(demo).toContainText('a thousand sleeping souls walk home')

  await demo.getByRole('button', { name: 'Start over' }).click()
  await expect(demo.getByRole('link', { name: /Create your first story free/ })).toHaveCount(0)
  await demo.getByRole('button', { name: 'Ember — enter the gate of living fire' }).click()
  await demo.getByRole('button', { name: 'Walk through the blaze' }).click()
  await demo.getByRole('button', { name: 'Face what waits inside' }).click()
  await expect(demo.getByRole('button', { name: 'Slip into its shadow and strike' })).toHaveCount(0)
  await expect(demo.getByRole('button', { name: 'Let the spirit speak your true name' })).toHaveCount(0)
  await demo.getByRole('button', { name: 'Burn the darkness with your last ember' }).click()
  await expect(demo).toContainText('The crown settles on your brow')
  await expect(demo).toContainText('the Ember Keeper waits for the next footsteps')
})

test('uses a remembered relic to break the curse and offers a way to walk away', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 844 })
  await page.goto('/')
  const demo = page.locator('#try-it')
  await demo.getByRole('button', { name: 'Ember — enter the gate of living fire' }).click()
  await demo.getByRole('button', { name: 'Tame the fire. Take the sigil.' }).click()
  await expect(demo).toContainText('Its inscription calls you the Ember Keeper')
  await demo.getByRole('button', { name: 'Carry the sigil to the throne' }).click()
  await expect(demo.getByRole('button', { name: 'Let the spirit speak your true name' })).toHaveCount(0)
  await demo.getByRole('button', { name: 'Fit the stolen sigil into the crown' }).click()
  await expect(demo).toContainText('The prison opens')
  await expect(demo).toContainText('a thousand sleeping souls walk home')

  await demo.getByRole('button', { name: 'Start over' }).click()
  await demo.getByRole('button', { name: 'Blade — cross the bridge of sentries' }).click()
  await demo.getByRole('button', { name: 'Cut the bridge loose. Leap alone.' }).click()
  await demo.getByRole('button', { name: 'Face what waits inside' }).click()
  await demo.getByRole('button', { name: 'Leave the crown. Choose the dawn.' }).click()
  await expect(demo).toContainText('Let the citadel remember the Last Blade')
  await expect(demo.getByRole('link', { name: /Create your first story free/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
})
