name: Playwright Tests
on:
  #push:
  #  branches: [main]
  #  Per algun motiu falla l'auth dels tests, però en local no. Els envs estan bé. Sembla que no troba l'input de mail, però hi és
  #  És molt possible que tingui a veure amb el setup i l'.auth/user.json
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
